name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Start Xvfb
        run: |
          sudo apt-get install -y xvfb  
          Xvfb :99 -ac &

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
          fonts-liberation \
          libappindicator3-1 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcups2 \
          libdbus-glib-1-2 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          libnss3 \
          libx11-xcb1 \
          libxcomposite1 \
          libxrandr2 \
          libxss1 \
          libxtst6 \
          xdg-utils




      # Frontend Tests
      - name: Set up HTTP server for frontend
        working-directory: ./frontenddevelopment
        run: |
          python3 -m http.server 8080 &
        env:
          PYTHONUNBUFFERED: 1

      - name: Install WebDriverIO dependencies
        working-directory: ./frontenddevelopment
        run: |
          npm install @wdio/cli 
          npx wdio config --yes  # Automatically accept defaults without prompts
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt-get update 
          sudo apt-get install -y wget unzip  
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)  
          DRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)  
          curl -Lo chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chromedriver-linux64.zip  
          unzip chromedriver.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin/  
          chromedriver --version  

      - name: Verify Chrome and ChromeDriver versions
        working-directory: ./frontenddevelopment
        run: |
          which google-chrome  
          which chromedriver 
          google-chrome --version
          chromedriver --version

      - name: Install Sentry SDK (Frontend)
        working-directory: ./frontenddevelopment
        run: |
          npm install @sentry/node @sentry/tracing
          echo "Sentry SDK installed for frontend"

      - name: Run WebDriverIO tests
        working-directory: ./frontenddevelopment
        run: |
          npx wdio run wdio.conf.js
        env:
          BASE_URL: http://localhost:8080
          DISPLAY: ':99'
          IMAGE_PATH: 'assets/picture.jpg'
          SENTRY_DSN: 'https://c2b33b72dfd69941a92a061c07e8a8d6@o4508620219219973.ingest.de.sentry.io/4508620228722768'



      # Backend Tests
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 23


      - name: Install backend dependencies
        working-directory: ./backend-test-automation
        run: npm ci

      - name: Install Sentry SDK (Backend)
        working-directory: ./backend-test-automation
        run: |
          npm install @sentry/node
          echo "Sentry SDK installed for backend"

      - name: Run backend tests
        working-directory: ./backend-test-automation
        run: npm test
        env:
          SENTRY_DSN: 'https://c2b33b72dfd69941a92a061c07e8a8d6@o4508620219219973.ingest.de.sentry.io/4508620228722768'

      # Upload Test Reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            ./frontenddevelopment/test-results
            ./backend-test-automation/coverage
