name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js (Version to be used for both frontend and backend)
      - name: Set up Node.js for frontend and backend
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Specify the version that works for both sections

      # Install Chrome Dependencies for WebDriverIO
      - name: Install Chrome Dependencies
        run: |  
          sudo apt-get update  
          sudo apt-get install -y \
            libxss1 \
            libappindicator3-1 \
            libgconf-2-4 \
            fonts-liberation \
            libnss3 \
            xvfb \
            wget unzip \
            google-chrome-stable  

      # Set up HTTP server for frontend
      - name: Set up HTTP server for frontend
        working-directory: ./frontenddevelopment
        run: |  
          python3 -m http.server 8080 &
        env:
          PYTHONUNBUFFERED: 1

      # Install WebdriverIO and run configuration setup
      - name: Install WebdriverIO
        working-directory: ./frontenddevelopment
        run: |  
          npm install @wdio/cli  
          
          npx wdio config --yes  # Uncomment if setting up for the first time  

      # Install ChromeDriver
      - name: Install ChromeDriver
        run: |  
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)  
          DRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)  
          curl -Lo chromedriver.zip https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip  
          unzip chromedriver.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin/  
          chromedriver --version  

      # Verify Chrome and ChromeDriver versions
      - name: Verify Chrome and ChromeDriver versions
        run: |  
          which google-chrome  
          which chromedriver   
          google-chrome --version  
          chromedriver --version  

      # Run WebdriverIO tests
      - name: Run WebdriverIO tests
        working-directory: ./frontenddevelopment
        run: |  
          npx wdio run wdio.conf.js
        env:
          BASE_URL: http://localhost:8080

      # Backend Tests
      - name: Install backend dependencies
        working-directory: ./backend-test-automation
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend-test-automation
        run: npm test

      # Upload Test Reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |  
            ./frontenddevelopment/test-results  
            ./backend-test-automation/coverage